apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: s3-store
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
  preservePoolsOnDelete: true
  gateway:
    type: s3
    sslCertificateRef:
    port: 80
    #securePort: 443
    instances: 1
    annotations:
    #  key: value
    # placement:
    #  nodeAffinity:
    #    requiredDuringSchedulingIgnoredDuringExecution:
    #      nodeSelectorTerms:
    #      - matchExpressions:
    #        - key: storage-node
    #          operator: In
    #          values:
    #          - "true"
    # #  tolerations:
    # #  - key: rgw-node
    # #    operator: Exists
    # #  podAffinity:
    # #  podAntiAffinity:
    # #  topologySpreadConstraints:
    # resources:
    # #  limits:
    # #    cpu: "500m"
    # #    memory: "1024Mi"
    # #  requests:
    # #    cpu: "500m"
    # #    memory: "1024Mi"
  healthCheck:
    bucket:
      disabled: false
      interval: 60s