apiVersion: v1
kind: Service
metadata:
  name: rook-prometheus
  namespace: rook-ceph
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: http
  selector:
    prometheus: rook-prometheus
