apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
  namespace: monit
  labels:
    app: thanos-query
    thanos-peers: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-query
      thanos-peers: "true"
  template:
    metadata:
      labels:
        app: thanos-query
        thanos-peers: "true"
    spec:
      containers:
      - name: thanos-query
        image: quay.io/thanos/thanos:v0.17.0
        args:
        - query
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:9090
        - --log.level=info
        - --log.format=logfmt
        - --query.replica-label=prometheus_replica
        - --query.replica-label=rule_replica
        - --store=dnssrv+_grpc._tcp.thanos-store.monit.svc.cluster.local
        #- --store=dnssrv+_grpc._tcp.prometheus-operated.monit.svc.cluster.local
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        - name: cluster
          containerPort: 10900