apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-store
  namespace: monit
  labels:
    app: thanos-store
    thanos-peer: "true"
spec:
  serviceName: "thanos-store"
  replicas: 1
  selector:
    matchLabels:
      app: thanos-store
      thanos-peer: "true"
  template:
    metadata:
      labels:
        app: thanos-store
        thanos-peer: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10902"
    spec:
      containers:
      - name: thanos-store
        # Always use explicit image tags (release or master-<date>-sha) instead of ambigous `latest` or `master`.
        image: quay.io/thanos/thanos:v0.17.0
        args:
        - store
        - --log.level=info
        - --log.format=logfmt
        - --data-dir=/var/thanos/store
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --objstore.config-file=/config/thanos-store.yml
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        - name: cluster
          containerPort: 10900
        volumeMounts:
        - name: config
          mountPath: /config/
          readOnly: true
        - name: data
          mountPath: /var/thanos/store
      volumes:
      - name: data
        emptyDir: {}
      - name: config
        configMap:
          name: thanos-store-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-store-config
  namespace: monit
data:
  thanos-store.yml: |-
    type: s3
    config:
      bucket: thanos
      endpoint: minio-test:9000
      access_key: minio
      secret_key: minio123
      insecure: true
      signature_version2: false
