grafana:
  persistence:
    enabled: true
    storageClassName: rook-ceph-block
  ingress:
    enabled: true
    hosts:
      - cluster.local
  additionalDataSources:
    - name: Prometheus
      type: prometheus
      url: thanos-query:9090
      access: proxy
      isDefault: true
  sidecar:
    datasources:
      defaultDatasourceEnabled: false
prometheus:
  retention: 12h
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: "baremetal"
        static_configs:
          - targets: ["192.168.3.82:9100","192.168.3.83:9100","192.168.3.81:9100","192.168.3.84:9100"]
    externalLabels:
      cluster: kraken # Add a cluster tag to distinguish clusters
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: rook-ceph-block
          resources:
            requests:
              storage: 10Gi
    thanos:
      baseImage: quay.io/thanos/thanos
      version: v0.17.0
      objectStorageConfig:
        key: thanos.yaml
        name: thanos-objectstorage
