# grafana:
#   persistence:
#     enabled: true
#     storageClassName: rook-ceph-block
#   ingress:
#     enabled: true
#     hosts:
#       - cluster.local
#   additionalDataSources:
#     - name: Kraken-Thanos
#       type: prometheus
#       url: thanos-query:9090
#       access: proxy
#       isDefault: true
#   sidecar:
#     datasources:
#       defaultDatasourceEnabled: false
prometheus:
  #retention: 12h
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: "baremetal-servers"
        static_configs:
          - targets: ["192.168.3.82:9100","192.168.3.83:9100","192.168.3.81:9100","192.168.3.84:9100"]

      - job_name: "haproxy-masters"
        static_configs:
          - targets: ["192.168.3.98:8404","192.168.3.99:8404","192.168.3.100:8404"]

      - job_name: "keepalived-masters"
        static_configs:
          - targets: ["192.168.3.98:9856","192.168.3.99:9856","192.168.3.100:9856"]
    externalLabels:
      cluster: kraken # Add a cluster tag to distinguish clusters
    # storageSpec:
    #   volumeClaimTemplate:
    #     spec:
    #       storageClassName: rook-ceph-block
    #       resources:
    #         requests:
    #           storage: 100Gi
    thanos:
      baseImage: quay.io/thanos/thanos
      version: v0.17.2
      objectStorageConfig:
        key: thanos.yaml
        name: thanos-objectstorage
