apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-compactor
  namespace: monit
  labels:
    app: thanos-compactor
    thanos-peer: "true"
spec:
  serviceName: "thanos-compactor"
  replicas: 1
  selector:
    matchLabels:
      app: thanos-compactor
      thanos-peer: "true"
  template:
    metadata:
      labels:
        app: thanos-compactor
        thanos-peer: "true"
    spec:
      containers:
      - name: thanos-compactor
        # Always use explicit image tags (release or master-<date>-sha) instead of ambigous `latest` or `master`.
        image: quay.io/thanos/thanos:v0.17.0
        args:
        - "compact"
        - "--log.level=debug"
        - "--data-dir=/var/thanos/store"
        - "--objstore.config-file=/thanos.yaml"
        - "--wait"
        ports:
        - name: http
          containerPort: 10902
        volumeMounts:
        - name: thanos-objectstorage
          mountPath: /
          readOnly: true
        - name: thanos-objectstorage
          mountPath: /var/thanos/store
      volumes:
      - name: data
        emptyDir: {}
      - name: config
        configMap:
          name: thanos-objectstorage