apiVersion: v1
kind: Service
metadata:
  name: grafana-external
  namespace: monitoring
  labels:
    app: grafana
spec:
  ports:
  - name: grafana
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-0-service
  namespace: monitoring
  labels:
    app: prometheus-0-service
spec:
  ports:
  - name: prometheus-0-service
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: prometheus-0-service
  sessionAffinity: None
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-1-service
  namespace: monitoring
  labels:
    app: prometheus-1-service
spec:
  ports:
  - name: prometheus-1-service
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: prometheus-1-service
  sessionAffinity: None
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-2-service
  namespace: monitoring
  labels:
    app: prometheus-2-service
spec:
  ports:
  - name: prometheus-2-service
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: prometheus-2-service
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-querier-external
  namespace: monitoring
  labels:
    app: thanos-querier
spec:
  ports:
  - name: thanos-querier
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: thanos-querier
  sessionAffinity: None
  type: NodePort



