apiVersion: v1
kind: Service
metadata:
  name: grafana-external
  namespace: monitoring
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/instance: grafana-prom-stack
    app.kubernetes.io/name: grafana
spec:
  ports:
    - name: grafana
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/instance: grafana-prom-stack
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: thanos-querier-ext
  namespace: monitoring
  labels:
    app: thanos-querier
spec:
  ports:
  - name: thanos-querier
    port: 10902
    protocol: TCP
    targetPort: 10902
  selector:
    app: thanos-querier
  sessionAffinity: None
  type: NodePort

---


