# apiVersion: discovery.k8s.io/v1beta1
# kind: EndpointSlice
# metadata:
#   name: kvm-monitor
#   labels:
#     k8s-app: external-server
# addressType: IPv4
# ports:
#   - name: metrics
#     protocol: TCP
#     port: 9100
# endpoints:
#   - addresses:
#       - "192.168.3.82"

# apiVersion: v1
# kind: Endpoints
# metadata:
#   name: external-server
#   labels:
#     k8s-app: external-server
# subsets:
# - addresses:
#   - ip: 192.168.3.82
#   ports:
#   - name: metrics
#     port: 9100
#     protocol: TCP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: kvm-metrics-k8s
  labels:
    k8s-app: kvm-metrics
subsets:
  - addresses:
    - ip: 192.168.3.82
    ports:
    - name: metrics
      port: 9100
      protocol: TCP