# kind: Service
# apiVersion: v1
# metadata:
#     name: kvm-monitor
#     labels:
#         #k8s-app: kvm-monitor
#         release: prometheus-operator
# spec:
#  type: ClusterIP
#  ports:
#  - name: metrics
#    port: 9100
#    targetPort: 9100
#    protocol: TCP

# apiVersion: v1
# kind: Service
# metadata:
#     name: kvm-metrics-svc
#     namespace: monit
#     labels:
#         k8s-app: kvm-metrics
# spec:
#     type: ExternalName
#     externalName: 192.168.3.82
#     clusterIP: ""
#     ports:
    # - name: metrics
    #   port: 9100
    #   protocol: TCP
#       targetPort: 9100


apiVersion: v1
kind: Service
metadata:
  name: kvm-metrics-k8s
  labels:
    k8s-app: kvm-metrics
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100

